# Generated by Django 6.0.7 on 2026-07-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('faturamento_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'permissions': [('view_relatorio_vendas', 'Pode visualizar o faturamento')],
            },
        ),
    ]
